/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedIdeasRouteImport } from './routes/_authenticated.ideas'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated.habits'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedIdeasIdeaIdRouteImport } from './routes/_authenticated.ideas.$ideaId'
import { Route as AuthenticatedAuthGoogleCallbackRouteImport } from './routes/_authenticated.auth.google.callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdeasRoute = AuthenticatedIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdeasIdeaIdRoute =
  AuthenticatedIdeasIdeaIdRouteImport.update({
    id: '/$ideaId',
    path: '/$ideaId',
    getParentRoute: () => AuthenticatedIdeasRoute,
  } as any)
const AuthenticatedAuthGoogleCallbackRoute =
  AuthenticatedAuthGoogleCallbackRouteImport.update({
    id: '/auth/google/callback',
    path: '/auth/google/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/ideas': typeof AuthenticatedIdeasRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/ideas/$ideaId': typeof AuthenticatedIdeasIdeaIdRoute
  '/auth/google/callback': typeof AuthenticatedAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/ideas': typeof AuthenticatedIdeasRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/ideas/$ideaId': typeof AuthenticatedIdeasIdeaIdRoute
  '/auth/google/callback': typeof AuthenticatedAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/ideas': typeof AuthenticatedIdeasRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ideas/$ideaId': typeof AuthenticatedIdeasIdeaIdRoute
  '/_authenticated/auth/google/callback': typeof AuthenticatedAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/habits'
    | '/ideas'
    | '/settings'
    | '/tasks'
    | '/ideas/$ideaId'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/habits'
    | '/ideas'
    | '/settings'
    | '/tasks'
    | '/'
    | '/ideas/$ideaId'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/calendar'
    | '/_authenticated/habits'
    | '/_authenticated/ideas'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/ideas/$ideaId'
    | '/_authenticated/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ideas': {
      id: '/_authenticated/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AuthenticatedIdeasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ideas/$ideaId': {
      id: '/_authenticated/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof AuthenticatedIdeasIdeaIdRouteImport
      parentRoute: typeof AuthenticatedIdeasRoute
    }
    '/_authenticated/auth/google/callback': {
      id: '/_authenticated/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthenticatedAuthGoogleCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedIdeasRouteChildren {
  AuthenticatedIdeasIdeaIdRoute: typeof AuthenticatedIdeasIdeaIdRoute
}

const AuthenticatedIdeasRouteChildren: AuthenticatedIdeasRouteChildren = {
  AuthenticatedIdeasIdeaIdRoute: AuthenticatedIdeasIdeaIdRoute,
}

const AuthenticatedIdeasRouteWithChildren =
  AuthenticatedIdeasRoute._addFileChildren(AuthenticatedIdeasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedIdeasRoute: typeof AuthenticatedIdeasRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuthGoogleCallbackRoute: typeof AuthenticatedAuthGoogleCallbackRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedIdeasRoute: AuthenticatedIdeasRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuthGoogleCallbackRoute: AuthenticatedAuthGoogleCallbackRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
